import React, { useState } from 'react';
import { Patient, TestCatalogItem, LabOrder, PaymentMethod, Gender } from '../types/lims';
import { formatPKR, formatCNIC, formatPakistaniPhone } from '../utils/formatters';

interface NewOrderModalProps {
  patients: Patient[];
  catalog: TestCatalogItem[];
  initialPatientId?: string;
  initialTests?: string[];
  initialNotes?: string;
  onSaveOrder: (newOrder: LabOrder, newPatient?: Patient) => void;
  onClose: () => void;
}

export const NewOrderModal: React.FC<NewOrderModalProps> = ({
  patients,
  catalog,
  initialPatientId,
  initialTests,
  initialNotes,
  onSaveOrder,
  onClose
}) => {
  // Step / Tab: 'select_patient' | 'create_patient'
  const [patientMode, setPatientMode] = useState<'existing' | 'new'>('existing');
  const [selectedPatientId, setSelectedPatientId] = useState<string>(initialPatientId || patients[0]?.id || '');
  const [patientSearch, setPatientSearch] = useState('');

  // New Patient Form state
  const nextPatientNum = patients.length + 1;
  const autoGeneratedPatientId = `PAT-2026-${String(nextPatientNum).padStart(4, '0')}`;
  const [newName, setNewName] = useState('');
  const [newAge, setNewAge] = useState<number>(30);
  const [newGender, setNewGender] = useState<Gender>('Male');
  const [newPhone, setNewPhone] = useState('0300-');
  const [newCnic, setNewCnic] = useState('');
  const [newAddress, setNewAddress] = useState('Lahore, Pakistan');
  const [referredBy, setReferredBy] = useState('');

  // Order Details state
  const [selectedTests, setSelectedTests] = useState<string[]>(
    initialTests && initialTests.length > 0 ? initialTests : ['CBC']
  );
  const [testSearch, setTestSearch] = useState('');
  const [discountType, setDiscountType] = useState<'flat' | 'percentage'>('flat');
  const [discountValue, setDiscountValue] = useState<number>(0);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('Cash');
  const [paidAmount, setPaidAmount] = useState<number>(0);
  const [orderNotes, setOrderNotes] = useState(initialNotes || '');
  const [formError, setFormError] = useState<string | null>(null);

  // Generate unique order ID and sample barcode
  const randomSuffix = Math.floor(1000 + Math.random() * 9000);
  const generatedOrderId = `ORD-${9400 + patients.length + randomSuffix % 100}`;
  const generatedBarcode = `BC-${Math.floor(100000 + Math.random() * 900000)}`;

  // Financial calculations in PKR
  const testObjects = catalog.filter(t => selectedTests.includes(t.code));
  const grossTotal = testObjects.reduce((acc, t) => acc + t.fee, 0);

  const discountPKR = discountType === 'percentage'
    ? Math.round((grossTotal * (discountValue || 0)) / 100)
    : Math.min(grossTotal, Number(discountValue) || 0);

  const netPayable = Math.max(0, grossTotal - discountPKR);

  // Initialize paid amount whenever netPayable changes if user hasn't typed custom
  const [paidCustom, setPaidCustom] = useState(false);
  const currentPaid = paidCustom ? paidAmount : netPayable;

  // Filter existing patients
  const filteredPatients = patients.filter(p =>
    p.name.toLowerCase().includes(patientSearch.toLowerCase()) ||
    p.phone.includes(patientSearch) ||
    p.cnic.includes(patientSearch) ||
    p.id.toLowerCase().includes(patientSearch.toLowerCase())
  );

  const toggleTest = (code: string) => {
    setFormError(null);
    if (selectedTests.includes(code)) {
      if (selectedTests.length > 1) {
        setSelectedTests(selectedTests.filter(c => c !== code));
      }
    } else {
      setSelectedTests([...selectedTests, code]);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    if (selectedTests.length === 0) {
      setFormError('Please select at least one laboratory test to proceed.');
      return;
    }

    let effectivePatientId = selectedPatientId;
    let createdPatient: Patient | undefined;

    if (patientMode === 'new') {
      if (!newName.trim()) {
        setFormError('Please enter patient full name to register.');
        return;
      }
      effectivePatientId = autoGeneratedPatientId;
      createdPatient = {
        id: autoGeneratedPatientId,
        name: newName.trim(),
        age: Number(newAge),
        gender: newGender,
        phone: newPhone,
        cnic: newCnic,
        address: newAddress,
        referredBy: referredBy || 'Self',
        createdAt: new Date().toISOString()
      };
    }

    // Determine specimen types combined
    const specimens = Array.from(new Set(testObjects.map(t => t.specimen))).join(' + ');

    // Determine Payment Status
    let paymentStatus: 'Paid' | 'Partial' | 'Unpaid' = 'Unpaid';
    if (currentPaid >= netPayable) {
      paymentStatus = 'Paid';
    } else if (currentPaid > 0) {
      paymentStatus = 'Partial';
    }

    const newOrder: LabOrder = {
      id: generatedOrderId,
      patientId: effectivePatientId,
      bookingDate: new Date().toISOString(),
      tests: selectedTests,
      sampleBarcode: generatedBarcode,
      sampleType: specimens || 'Specimen Tube',
      sampleStatus: 'Sample Pending',
      totalAmount: grossTotal,
      discount: discountPKR,
      discountType,
      discountPercentage: discountType === 'percentage' ? discountValue : undefined,
      netAmount: netPayable,
      paidAmount: currentPaid,
      paymentStatus,
      paymentMethod,
      referredByDoctor: referredBy || (patientMode === 'existing' ? (patients.find(p => p.id === selectedPatientId)?.referredBy || 'Self') : 'Self'),
      notes: orderNotes
    };

    onSaveOrder(newOrder, createdPatient);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-3 sm:p-4 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-xl shadow-2xl max-w-3xl w-full my-6 overflow-hidden border border-slate-200 flex flex-col max-h-[92vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-slate-50">
          <div>
            <h2 className="text-base font-bold text-slate-800 flex items-center gap-2">
              <span className="w-2.5 h-2.5 rounded-full bg-teal-500 inline-block" />
              Book New Lab Order / Specimen
            </h2>
            <p className="text-xs text-slate-500">
              System Order: <strong className="font-mono text-teal-700">{generatedOrderId}</strong> · Barcode: <strong className="font-mono text-slate-700">{generatedBarcode}</strong>
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 p-1.5 rounded-lg text-lg leading-none"
          >
            ✕
          </button>
        </div>

        <form onSubmit={handleSubmit} className="overflow-y-auto p-6 space-y-6 text-xs">
          {formError && (
            <div className="p-3 bg-rose-50 border border-rose-200 rounded-lg text-rose-700 flex items-center justify-between">
              <span className="font-semibold">{formError}</span>
              <button
                type="button"
                onClick={() => setFormError(null)}
                className="text-rose-500 hover:text-rose-800 text-sm font-bold"
              >
                ✕
              </button>
            </div>
          )}

          {/* Section 1: Patient Information */}
          <div className="bg-slate-50/70 border border-slate-200 rounded-lg p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="font-bold text-slate-800 uppercase tracking-wider text-[11px]">
                1. Patient Information
              </span>
              <div className="flex bg-slate-200 p-0.5 rounded-lg">
                <button
                  type="button"
                  onClick={() => setPatientMode('existing')}
                  className={`px-3 py-1 rounded-md transition-colors ${
                    patientMode === 'existing' ? 'bg-white text-slate-900 font-semibold shadow-xs' : 'text-slate-600'
                  }`}
                >
                  Existing Patient
                </button>
                <button
                  type="button"
                  onClick={() => setPatientMode('new')}
                  className={`px-3 py-1 rounded-md transition-colors ${
                    patientMode === 'new' ? 'bg-white text-teal-700 font-semibold shadow-xs' : 'text-slate-600'
                  }`}
                >
                  + Register New Patient
                </button>
              </div>
            </div>

            {patientMode === 'existing' ? (
              <div>
                <div className="mb-2">
                  <input
                    type="text"
                    placeholder="Search by Patient Name, Phone, CNIC or ID..."
                    value={patientSearch}
                    onChange={(e) => setPatientSearch(e.target.value)}
                    className="w-full bg-white border border-slate-300 rounded-lg px-3 py-2 text-xs focus:ring-1 focus:ring-teal-500 focus:border-teal-500"
                  />
                </div>
                <div className="max-h-36 overflow-y-auto border border-slate-200 rounded-lg bg-white divide-y divide-slate-100">
                  {filteredPatients.map((pat) => (
                    <label
                      key={pat.id}
                      className={`flex items-center justify-between p-2.5 cursor-pointer hover:bg-teal-50/50 ${
                        selectedPatientId === pat.id ? 'bg-teal-50/90 font-medium' : ''
                      }`}
                    >
                      <div className="flex items-center gap-2">
                        <input
                          type="radio"
                          name="selectedPatient"
                          checked={selectedPatientId === pat.id}
                          onChange={() => setSelectedPatientId(pat.id)}
                          className="text-teal-600 focus:ring-teal-500"
                        />
                        <div>
                          <span className="font-bold text-slate-800 mr-2">{pat.name}</span>
                          <span className="text-slate-500 font-mono text-[11px]">({pat.id})</span>
                          <div className="text-[10px] text-slate-500">
                            {pat.gender}, {pat.age} yrs · Phone: {pat.phone} · CNIC: {pat.cnic || 'N/A'}
                          </div>
                        </div>
                      </div>
                      <span className="text-[11px] text-slate-400 truncate max-w-[140px]">
                        {pat.address}
                      </span>
                    </label>
                  ))}
                  {filteredPatients.length === 0 && (
                    <div className="p-4 text-center text-slate-400">
                      No patients matched search. Click "+ Register New Patient" above.
                    </div>
                  )}
                </div>
              </div>
            ) : (
              /* New Patient Quick Form */
              <div className="space-y-3">
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div>
                    <label className="block text-slate-600 font-semibold mb-1">
                      System Generated ID
                    </label>
                    <input
                      type="text"
                      disabled
                      value={autoGeneratedPatientId}
                      className="w-full bg-slate-100 border border-slate-300 rounded-lg px-2.5 py-1.5 font-mono font-bold text-teal-800"
                    />
                  </div>
                  <div className="sm:col-span-2">
                    <label className="block text-slate-700 font-semibold mb-1">
                      Patient Full Name *
                    </label>
                    <input
                      type="text"
                      required
                      placeholder="e.g. Tariq Mehmood"
                      value={newName}
                      onChange={(e) => setNewName(e.target.value)}
                      className="w-full bg-white border border-slate-300 rounded-lg px-2.5 py-1.5 focus:border-teal-500 focus:ring-1 focus:ring-teal-500"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-slate-700 font-semibold mb-1">Age (Years)</label>
                    <input
                      type="number"
                      min={0}
                      max={120}
                      value={newAge}
                      onChange={(e) => setNewAge(Number(e.target.value))}
                      className="w-full bg-white border border-slate-300 rounded-lg px-2.5 py-1.5"
                    />
                  </div>
                  <div>
                    <label className="block text-slate-700 font-semibold mb-1">Gender</label>
                    <select
                      value={newGender}
                      onChange={(e) => setNewGender(e.target.value as Gender)}
                      className="w-full bg-white border border-slate-300 rounded-lg px-2.5 py-1.5"
                    >
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-slate-700 font-semibold mb-1">Phone (03xx)</label>
                    <input
                      type="text"
                      placeholder="0300-1234567"
                      value={newPhone}
                      onChange={(e) => setNewPhone(formatPakistaniPhone(e.target.value))}
                      className="w-full bg-white border border-slate-300 rounded-lg px-2.5 py-1.5 font-mono"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <div>
                    <label className="block text-slate-700 font-semibold mb-1">
                      CNIC No. (xxxxx-xxxxxxx-x)
                    </label>
                    <input
                      type="text"
                      placeholder="35201-1234567-1"
                      value={newCnic}
                      onChange={(e) => setNewCnic(formatCNIC(e.target.value))}
                      className="w-full bg-white border border-slate-300 rounded-lg px-2.5 py-1.5 font-mono"
                    />
                  </div>
                  <div>
                    <label className="block text-slate-700 font-semibold mb-1">
                      Address (Area / City)
                    </label>
                    <input
                      type="text"
                      placeholder="e.g. Gulberg III, Lahore"
                      value={newAddress}
                      onChange={(e) => setNewAddress(e.target.value)}
                      className="w-full bg-white border border-slate-300 rounded-lg px-2.5 py-1.5"
                    />
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Section 2: Test Catalog Selection with subheadings check & fee */}
          <div className="bg-slate-50/70 border border-slate-200 rounded-lg p-4">
            <div className="flex items-center justify-between mb-2">
              <span className="font-bold text-slate-800 uppercase tracking-wider text-[11px]">
                2. Select Investigations / Tests
              </span>
              <span className="text-xs text-slate-500 font-semibold">
                {selectedTests.length} tests selected · Subtotal: <span className="text-teal-700 font-bold">{formatPKR(grossTotal)}</span>
              </span>
            </div>

            <div className="mb-2">
              <input
                type="text"
                placeholder="Filter tests by name or code (e.g. CBC, LFT, RFT, Urine)..."
                value={testSearch}
                onChange={(e) => setTestSearch(e.target.value)}
                className="w-full bg-white border border-slate-300 rounded-lg px-3 py-1.5 text-xs"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-h-48 overflow-y-auto p-1">
              {catalog
                .filter(t =>
                  t.name.toLowerCase().includes(testSearch.toLowerCase()) ||
                  t.code.toLowerCase().includes(testSearch.toLowerCase()) ||
                  t.category.toLowerCase().includes(testSearch.toLowerCase())
                )
                .map((test) => {
                  const isChecked = selectedTests.includes(test.code);
                  return (
                    <label
                      key={test.code}
                      onClick={() => toggleTest(test.code)}
                      className={`flex items-start justify-between p-2.5 rounded-lg border cursor-pointer transition-colors ${
                        isChecked
                          ? 'border-teal-500 bg-teal-50/70 text-slate-900'
                          : 'border-slate-200 bg-white hover:border-slate-300 text-slate-700'
                      }`}
                    >
                      <div className="flex items-start gap-2">
                        <input
                          type="checkbox"
                          checked={isChecked}
                          onChange={() => {}} // handled by parent onClick
                          className="mt-0.5 rounded text-teal-600 focus:ring-teal-500"
                        />
                        <div>
                          <div className="font-bold text-xs flex items-center gap-1.5">
                            <span className="font-mono text-teal-800">{test.code}</span>
                            <span>{test.name}</span>
                          </div>
                          <div className="text-[10px] text-slate-500">
                            {test.category} · {test.subHeadings?.length || 0} sub-heading sections
                          </div>
                        </div>
                      </div>
                      <span className="font-mono font-bold text-slate-900 tabular-nums shrink-0 ml-2">
                        {formatPKR(test.fee)}
                      </span>
                    </label>
                  );
                })}
            </div>
          </div>

          {/* Section 3: Billing & Pricing in PKR */}
          <div className="bg-slate-50/70 border border-slate-200 rounded-lg p-4">
            <span className="font-bold text-slate-800 uppercase tracking-wider text-[11px] block mb-3">
              3. Pricing & Billing (PKR)
            </span>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {/* Discount settings */}
              <div>
                <label className="block text-slate-700 font-semibold mb-1">Discount</label>
                <div className="flex gap-1">
                  <select
                    value={discountType}
                    onChange={(e) => setDiscountType(e.target.value as 'flat' | 'percentage')}
                    className="bg-white border border-slate-300 rounded-lg px-2 py-1.5 text-xs"
                  >
                    <option value="flat">PKR (Rs.)</option>
                    <option value="percentage">% Percent</option>
                  </select>
                  <input
                    type="number"
                    min={0}
                    value={discountValue}
                    onChange={(e) => {
                      setDiscountValue(Number(e.target.value));
                      setPaidCustom(false);
                    }}
                    className="w-full bg-white border border-slate-300 rounded-lg px-2 py-1.5 text-xs font-mono"
                  />
                </div>
              </div>

              {/* Payment Method */}
              <div>
                <label className="block text-slate-700 font-semibold mb-1">Payment Method</label>
                <select
                  value={paymentMethod}
                  onChange={(e) => setPaymentMethod(e.target.value as PaymentMethod)}
                  className="w-full bg-white border border-slate-300 rounded-lg px-2 py-1.5 text-xs font-medium"
                >
                  <option value="Cash">Cash Counter</option>
                  <option value="JazzCash">JazzCash</option>
                  <option value="EasyPaisa">EasyPaisa</option>
                  <option value="Bank Card / Transfer">Bank Card / 1Link</option>
                </select>
              </div>

              {/* Amount Paid Now */}
              <div>
                <label className="block text-slate-700 font-semibold mb-1">
                  Paid Amount (PKR)
                </label>
                <input
                  type="number"
                  min={0}
                  max={netPayable}
                  value={currentPaid}
                  onChange={(e) => {
                    setPaidAmount(Number(e.target.value));
                    setPaidCustom(true);
                  }}
                  className="w-full bg-white border border-slate-300 rounded-lg px-2 py-1.5 text-xs font-mono font-bold text-teal-800"
                />
              </div>
            </div>

            {/* Financial Summary Strip */}
            <div className="mt-4 p-3 bg-white rounded-lg border border-slate-200 flex flex-wrap items-center justify-between gap-4 font-mono text-xs">
              <div>
                <span className="text-slate-500 block text-[10px]">Gross Fee:</span>
                <span className="font-bold">{formatPKR(grossTotal)}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">Discount:</span>
                <span className="font-bold text-teal-700">- {formatPKR(discountPKR)}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">Net Payable:</span>
                <span className="font-bold text-slate-900 text-sm">{formatPKR(netPayable)}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">Received:</span>
                <span className="font-bold text-emerald-700">{formatPKR(currentPaid)}</span>
              </div>
              <div>
                <span className="text-slate-500 block text-[10px]">Balance Due:</span>
                <span className={`font-bold ${netPayable - currentPaid > 0 ? 'text-rose-600' : 'text-slate-600'}`}>
                  {formatPKR(Math.max(0, netPayable - currentPaid))}
                </span>
              </div>
            </div>

            <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-700 font-semibold mb-1">
                  Referred by Doctor / Clinic
                </label>
                <input
                  type="text"
                  placeholder="e.g. Dr. Salman Tariq / Self"
                  value={referredBy}
                  onChange={(e) => setReferredBy(e.target.value)}
                  className="w-full bg-white border border-slate-300 rounded-lg px-2 py-1.5 text-xs"
                />
              </div>
              <div>
                <label className="block text-slate-700 font-semibold mb-1">
                  Phlebotomy & Sample Notes
                </label>
                <input
                  type="text"
                  placeholder="e.g. Fasting 10 hrs, Urgent STAT report required"
                  value={orderNotes}
                  onChange={(e) => setOrderNotes(e.target.value)}
                  className="w-full bg-white border border-slate-300 rounded-lg px-2 py-1.5 text-xs"
                />
              </div>
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-5 py-2 text-xs font-bold text-white bg-teal-600 hover:bg-teal-700 rounded-lg shadow-sm transition-colors flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
              </svg>
              Complete Booking & Generate Barcode
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
